name: On Release Auto Upgrade

on:
  release: 
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        # with:
        #   ref: ${{ inputs.target-branch }}
      - name: CHECKS
        run: echo ${{ github.event.repository.default_branch }}

      - name: Running script
        run: bash ./scripts/empty_upgrade_handler_gen.sh 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: ${{ github.event.repository.default_branch }}
          body: |
            Update report
            - Created a new empty upgrade handler
            - Increased E2E_UPGRADE_VERSION in Makefile by 1
          labels: |
            T:auto
            C:e2e
            C:app-wiring
