# When new release is created this workflow will be triggered and will do 3 things:
# 1) it will create a directory with an empty upgrade handler in app/upgrades folder
# 2) will increase an E2E_UPGRADE_VERSION variable in Makefile
# 3) create a pull request with these changes to main 

name: On Release Auto Upgrade

on:
  release: 
    types: [created]
jobs:
  check_release_version:
    runs-on: ubuntu-latest
    # this script will create a new temp.txt file and write 1 to it if a new version is major (major == in version vX.Y.Z changed X)
    steps:
      - name: Check is release is major
        run: bash ./scripts/check_release.sh ${{ github.event.release.tag_name }}

  post_release:
    if: $(head -n 1 ./temp) == 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Running script
        run: |
          bash ./scripts/empty_upgrade_handler_gen.sh 
          rm -rf ./temp

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: ${{ github.event.repository.default_branch }}
          body: |
            Update report
            - Created a new empty upgrade handler
            - Increased E2E_UPGRADE_VERSION in Makefile by 1
          labels: |
            T:auto
            C:e2e
            C:app-wiring
