name: On Release Auto Upgrade

on:
  release: 
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo ${{ github.head_ref }}
        uses: actions/checkout@v2.3.4

      - name: Running script
        run: bash ./scripts/empty_upgrade_handler_gen.sh 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          base: ${{ github.head_ref }}
          body: |
            Update report
            - Created a new empty upgrade handler
            - Increased E2E_UPGRADE_VERSION in Makefile by 1
          labels: |
            auto
            e2e
            app-wiring
